name: Compile Zygisk Loader

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Android NDK
      uses: android-actions/setup-android@v3
      with:
        ndk-version: '25.2.9519653'

    - name: Download zygisk.hpp Mandiri
      run: |
        curl -o zygisk.hpp https://githubusercontent.com

    - name: Compile Library (.so) via NDK
      run: |
        $ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang++ \
        -shared -fPIC main.cpp -o libzygisk_loader.so -llog

    - name: Packing Modul ke ZIP Magisk
      run: |
        mkdir -p zygisk_modul/zygisk
        cp libzygisk_loader.so zygisk_modul/zygisk/
        cp module.prop zygisk_modul/
        cd zygisk_modul && zip -r ../Zygisk-Loader-ESP-FFMAX.zip ./*

    - name: Upload Modul Siap Pakai
      uses: actions/artifacts@v4
      with:
        name: Zygisk-Loader-Magisk
        path: Zygisk-Loader-ESP-FFMAX.zip
