name: Compile Zygisk Loader

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Download zygisk.hpp Mandiri
      run: |
        curl -o zygisk.hpp https://githubusercontent.com

    - name: Compile Library (.so) via Clang
      run: |
        sudo apt-get update && sudo apt-get install -y g++-aarch64-linux-gnu zip
        aarch64-linux-gnu-g++ -shared -fPIC main.cpp -o libzygisk_loader.so

    - name: Packing Modul ke ZIP Magisk
      run: |
        mkdir -p zygisk_modul/zygisk
        cp libzygisk_loader.so zygisk_modul/zygisk/
        cp module.prop zygisk_modul/
        cd zygisk_modul && zip -r ../Zygisk-Loader-ESP-FFMAX.zip ./*

    - name: Upload Modul Siap Pakai
      uses: actions/upload-artifact@v4
      with:
        name: Zygisk-Loader-Magisk
        path: Zygisk-Loader-ESP-FFMAX.zip
